version: "3.9"

services:
    db:
     image: postgres:14
     container_name: db
     restart: always
     expose:
         - "3306"
     environment:
       POSTGRES_USER: admin
       POSTGRES_PASSWORD: password
       POSTGRES_DB: django

    redis:
        image: redis:7
        container_name: mini_redis
        restart: always
        expose:
            - "6379"

    frontend:
        build:
            context: ../../
            dockerfile: devops/docker/Dockerfile-frontend
        container_name: mini_frontend
        restart: always
        ports:
            - "3000:3000"
        volumes:
          - ../../frontend/:/minime/

    web:
        build:
            context: ../../
            dockerfile: devops/docker/Dockerfile-backend
        container_name: mini_app
        restart: always
        ports:
            - "8000:8000"
        environment:
            - DJANGO_DEBUG=True
            - REDIS_URL=rediscache://redis:6379/1?client_class=django_redis.client.DefaultClient&compressor=django_redis.compressors.zlib.ZlibCompressor
            - DATABASE_URL=postgres://admin:password@db:5432/django
        command: ["runserver"]
        volumes:
          - ../../:/minime/
        depends_on:
            - db
            - redis
