FROM python:3.11-slim

WORKDIR /minime
COPY . /minime

COPY devops/docker/docker-entrypoint.sh /usr/local/bin/

RUN pip install pipenv==2023.3.20 && \
    pipenv install --system --deploy

ENTRYPOINT ["docker-entrypoint.sh"]

EXPOSE 8000

CMD ["runserver"]
