apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    app: app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - image: bluecap/minime:latest
        name: app
        envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: app-secrets
        - configMapRef:
            name: postgres-config
        - secretRef:
            name: postgres-secrets
        env:
          - name: POSTGRES_HOST
            value: postgres-service
          - name: REDIS_HOST
            value: redis-service
          - name: DATABASE_URL
            value: postgres://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@$(POSTGRES_HOST):5432/$(POSTGRES_DB)
          - name: REDIS_URL
            value: rediscache://$(REDIS_HOST):6379/1?client_class=django_redis.client.DefaultClient&compressor=django_redis.compressors.zlib.ZlibCompressor
        ports:
          - containerPort: 8000
            name: gunicorn
      restartPolicy: Always
