# Generated by Django 2.1 on 2018-08-23 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.SlugField(max_length=6)),
                ('url', models.URLField(max_length=2048)),
                ('created', models.DateTimeField(auto_now=True)),
                ('count', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddIndex(
            model_name='url',
            index=models.Index(fields=['hash'], name='minime_url_hash_c04475_idx'),
        ),
    ]
