# Generated by Django 2.1.1 on 2018-09-01 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('minime', '0002_auto_20180830_1317'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('browser_family', models.CharField(max_length=100)),
                ('browser_version', models.CharField(max_length=100)),
                ('os_family', models.CharField(max_length=100)),
                ('os_version', models.CharField(max_length=100)),
                ('device', models.CharField(max_length=100)),
                ('platform', models.CharField(max_length=100)),
                ('is_mobile', models.BooleanField()),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minime.Url')),
            ],
        ),
    ]
