# Generated by Django 2.1.1 on 2018-09-10 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minime', '0003_visitors'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitors',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
